src/Entity/BD.php
<?php

namespace App\Entity;

use App\Repository\BDRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BDRepository::class)
 */
class BD
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=80)
     */
    private $titre;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="date")
     */
    private $date_publication;

    /**
     * @ORM\ManyToOne(targetEntity=Auteur::class, inversedBy="bDs")
     * @ORM\JoinColumn(nullable=false)
     */
    private $auteur;

    /**
     * @ORM\OneToMany(targetEntity=Cathegorie::class, mappedBy="bD")
     */
    private $cathegories;

    /**
     * @ORM\ManyToMany(targetEntity=Genre::class, inversedBy="bDs")
     */
    private $genre;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $FilePath;

    /**
     * @ORM\ManyToOne(targetEntity=Cathegorie::class, inversedBy="bDs")
     * @ORM\JoinColumn(nullable=false)
     */
    private $categorie;

    public function __construct()
    {
        $this->cathegories = new ArrayCollection();
        $this->genre = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDatePublication(): ?\DateTimeInterface
    {
        return $this->date_publication;
    }

    public function setDatePublication(\DateTimeInterface $date_publication): self
    {
        $this->date_publication = $date_publication;

        return $this;
    }

    public function getAuteur(): ?Auteur
    {
        return $this->auteur;
    }

    public function setAuteur(?Auteur $auteur): self
    {
        $this->auteur = $auteur;

        return $this;
    }

    /**
     * @return Collection|Cathegorie[]
     */
    public function getCathegories(): Collection
    {
        return $this->cathegories;
    }

    public function addCathegory(Cathegorie $cathegory): self
    {
        if (!$this->cathegories->contains($cathegory)) {
            $this->cathegories[] = $cathegory;
            $cathegory->setBD($this);
        }

        return $this;
    }

    public function removeCathegory(Cathegorie $cathegory): self
    {
        if ($this->cathegories->removeElement($cathegory)) {
            // set the owning side to null (unless already changed)
            if ($cathegory->getBD() === $this) {
                $cathegory->setBD(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Genre[]
     */
    public function getGenre(): Collection
    {
        return $this->genre;
    }

    public function addGenre(Genre $genre): self
    {
        if (!$this->genre->contains($genre)) {
            $this->genre[] = $genre;
        }

        return $this;
    }

    public function removeGenre(Genre $genre): self
    {
        $this->genre->removeElement($genre);

        return $this;
    }

    public function getFilePath(): ?string
    {
        return $this->FilePath;
    }

    public function setFilePath(?string $FilePath): self
    {
        $this->FilePath = $FilePath;

        return $this;
    }

    public function getCategorie(): ?Cathegorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Cathegorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }
}

src/Form/BDType.php
<?php

namespace App\Form;

use App\Entity\BD;
use App\Entity\Cathegorie;
use App\Entity\Genre;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Image;

class BDType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('titre')
            ->add('description')
            ->add('date_publication', DateType::class,[
                'data' => new \DateTime(),
                'format' => 'ddMMyyyy',
            ])
            ->add('categorie', EntityType::class,[
                'class' => Cathegorie::class,
                'choice_label' => 'libelle',
                'multiple' => false,
                'expanded' => true,
            ])
            ->add('genre', EntityType::class,[
                'class' => Genre::class,
                'choice_label' => 'libelle',
                'multiple' => true,
                'expanded' => true,
            ])
            ->add('FilePath', FileType::class,[
                'label' => 'Couverture',
                'mapped' => false,
                'constraints' => [
                    new Image()
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => BD::class,
        ]);
    }
}

src/Controller/BDController.php
<?php

namespace App\Controller;

use App\Entity\BD;
use App\Form\AddChapterType;
use App\Form\BDType;
use App\Repository\AuteurRepository;
use App\Repository\BDRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Doctrine\Migrations\Configuration\EntityManager;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Finder\Finder;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

/**
 * @Route("/b/d")
 */
class BDController extends AbstractController
{
    /**
     * @Route("/", name="b_d_index", methods={"GET"})
     */
    public function index(BDRepository $bDRepository, Filesystem $filesystem): Response
    {
        return $this->render('bd/index.html.twig', [
            'b_ds' => $bDRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="b_d_new", methods={"GET","POST"})
     */
    public function new(Filesystem $filesystem, Request $request, AuteurRepository $auteurRepository, SessionInterface $session): Response
    {
        $bD = new BD();
        $renseign_auteur = $auteurRepository->findOneBy([
            'nom' => $session->get('Nom'),
            'prenom' => $session->get('Prenom'),
            'pseudo' => $session->get('Pseudo')
        ]);
        $bD->setAuteur($renseign_auteur);
        $form = $this->createForm(BDType::class, $bD);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            
            $entityManager = $this->getDoctrine()->getManager();
            $coverFile = $form->get('FilePath')->getData();
            $path_in_database =$coverFile->getClientOriginalName();
            if ($coverFile){
                try{
                    $coverFile->move(
                        $this->getParameter('cover_directory'),
                        $path_in_database
                    );
                    $filesystem->mkdir('comics\\'.$form->get('titre')->getData());
                }catch (FileException $e){
                    $e->getMessage();
                }
                $bD->setFilePath($path_in_database);
            }
            $entityManager->persist($bD);
            $entityManager->flush();

            return $this->redirectToRoute('b_d_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('bd/new.html.twig', [
            'b_d' => $bD,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="b_d_show", methods={"GET","POST"})
     */
    public function show(BD $bD, Request $request, Filesystem $filesystem, SluggerInterface $slugger): Response {
        $dir = $this->getParameter('cover_directory').'\\'.$bD->getTitre();
        $finder = Finder::create()
            ->in($dir)
            ->directories();
        $files = iterator_to_array($finder,false);

        $form = $this->createForm(AddChapterType::class);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            $filePath = 'comics\\'.$bD->getTitre().'\\'.$form->get("Nom_du_chapitre")->getData();
            $filesystem->mkdir($filePath);
            $imgs = $request->files->get("add_chapter");
            foreach ($imgs["Selectionnez_un_chapitre"] as $img){
                try{
                    $img->move(
                        $filePath,
                        $img->getClientOriginalName()
                    );
                }catch (FileException $e){
                    $e->getMessage();
                }
            }
        }
        return $this->render('bd/show.html.twig', [
            'b_d' => $bD,
            'form' => $form->createView(),
            'chapters' => $files
        ]);
    }

    /**
     * @Route("/{id}/edit", name="b_d_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, BD $bD): Response
    {
        $form = $this->createForm(BDType::class, $bD);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('b_d_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('bd/edit.html.twig', [
            'b_d' => $bD,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="b_d_delete", methods={"POST"})
     */
    public function delete(Request $request, BD $bD, Filesystem $filesystem): Response
    {
        if ($this->isCsrfTokenValid('delete'.$bD->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($bD);
            $entityManager->flush();
        }

        try{
            $filesystem->remove("comics/".$bD->getTitre());
            $filesystem->remove("comics/".$bD->getFilePath());
        }catch (FileException $e){
            $e->getMessage();
        }
        return $this->redirectToRoute('b_d_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/bd/_delete_form.html.twig
<form method="post" action="{{ path('b_d_delete', {'id': b_d.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ b_d.id) }}">
    <button class="btn">Delete</button>
</form>

templates/bd/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/bd/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit BD{% endblock %}

{% block body %}
    <h1>Edit BD</h1>

    {{ include('bd/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('b_d_index') }}">back to list</a>

    {{ include('bd/_delete_form.html.twig') }}

{% endblock %}

templates/bd/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}BD index{% endblock %}

{% block body %}
    <h1>BD index</h1>

    <a href="{{ path('b_d_new') }}">Create new</a>
    <table class="table">
        <thead>
            <tr>
                <th>Titre</th>
                <th>Description</th>
                <th>Date_publication</th>
                <th>FilePath</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for b_d in b_ds %}
            <tr>
                <td>{{ b_d.titre }}</td>
                <td>{{ b_d.description }}</td>
                <td>{{ b_d.datePublication ? b_d.datePublication|date('Y-m-d') : '' }}</td>
                <td><img width="150px" src=" {{ asset('comics/'~b_d.FilePath) }}"></td>
                <td>
                    <a href="{{ path('b_d_show', {'id': b_d.id}) }}">show</a>
                    <a href="{{ path('b_d_edit', {'id': b_d.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/bd/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New BD{% endblock %}

{% block body %}
    <h1>Create new BD</h1>

    {{ include('bd/_form.html.twig') }}

    <a href="{{ path('b_d_index') }}">back to list</a>
{% endblock %}

templates/bd/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}BD{% endblock %}

{% block body %}
    <h1>BD</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ b_d.id }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ b_d.titre }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ b_d.description }}</td>
            </tr>
            <tr>
                <th>Date_publication</th>
                <td>{{ b_d.datePublication ? b_d.datePublication|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <td><img width="100px" src=" {{ asset('comics/'~b_d.FilePath) }}"></td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('b_d_index') }}">back to list</a>

    <a href="{{ path('b_d_edit', {'id': b_d.id}) }}">edit</a>


    {{ include('bd/_form.html.twig') }}
    <ul>
        {% for chapter in chapters %}
            <li>{{ chapter.fileName }}</li>
        {% endfor %}
    </ul>
{% endblock %}